# Generated by Django 6.1 on 2026-09-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='observacao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
